name: Deploy to Netlify

on:
  push:
    branches:
      - master  # Cambialo a 'main' si tu rama principal se llama así

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Desplegamos directamente usando el CLI oficial de Netlify
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=. --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}